name: nihao_kids
description: Aplikasi Belajar Bahasa Mandarin Interaktif untuk Anak TK dan SD
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  audioplayers: ^5.2.1
  google_mobile_ads: ^5.1.0
  unity_ads_plugin: ^0.5.0
  shared_preferences: ^2.2.2
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/audio/words/
    - assets/audio/sfx/
    - assets/images/
    - assets/hanzi_data.json
    - assets/hanzi_writer.min.js
